name = "Krydda Modpack"
author = "Krydda_Lorentz"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cb31f289f2d13baaafe847018194b7c62930117c2b29143512b0c8f45433a60"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
