peek_exploration_maps=false
peek_compasses=false
peek_recovery_compasses=false
peek_suspicious_stews=false
peek_ender_chests=true
show_shulker_box_item_hint=false
show_shulker_box_block_hint=false
show_shulker_box_labels=false
send_shulker_box_data_to_client=false
send_decorated_pot_data_to_client=false
